language: ruby
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
sudo: false
rvm:
  - 2.2.2
gemfile:
  - Gemfile
before_script:
  - export SECRET_KEY_BASE="$(bundle exec rake secret)"
  - psql -c 'create database forum_test;' -U postgres
addons:
  postgresql: 9.2
